version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: thomasgean/jenkinscustom:latest
    restart: always
    ports:
      - "8085:8080"
      - "50000:50000"
    networks:
      - jenkinsCI
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/var/jenkins_home/.kube
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For Docker Engine + Docker Desktop cross compatibility, requires daemon.json

  sonarqube:
    container_name: sonarqube-server
    image: sonarqube:7.9.6-community
    ports:
      - "9000:9000"
    networks:
      - jenkinsCI
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  jenkinsCI:
    name: jenkinsCI
    external: true
    driver: bridge

volumes:
  jenkins_home:
    external: true
  sonarqube_conf:
    external: true
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs:
    external: true
