kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 6443       # <--- K8s API server inside Kind
        hostPort: 43399           # <--- port reached from Jenkins
        listenAddress: "0.0.0.0"  # <--- Makes it accessible from Docker bridge (jenkinsCI is bridged)
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - localhost
            - 127.0.0.1
            - host.docker.internal
            - 172.17.0.1
            - 172.18.0.1
            - 192.168.4.1
