apiVersion: v1
kind: Service
metadata:
  name: mathlinux-service
spec:
  type: NodePort
  selector:
    app: mathlinux
  ports:
    - port: 80              # External access port
      targetPort: 8081      # Port inside the container
      nodePort: 30081       # Port exposed on the host (Other options: 30000–32767)
